import { join } from 'node:path';
import { scanTheme } from './theme-scanner';
import { applyRules, CC0_PACK_RULES } from './cc0-pack-metadata';
import type {
  AssetManifest,
  DecorationManifest,
  ProtectedBuildingManifest,
  TilesetManifest,
} from './types';

/**
 * Manifest for the `tiny-swords-cc0` editor theme. Shape mirrors the
 * default theme so every consumer (TilePalette, EditorScene, etc.)
 * sees the same record layout — only the paths differ.
 *
 * Tilesets and protected buildings are still hand-curated because they
 * carry pack-specific semantics (activity mappings, frame layouts) that
 * can't be inferred from filenames alone. Decorations, on
 * the other hand, are generated by walking the upstream folder tree and
 * applying declarative metadata rules (see `cc0-pack-metadata.ts`).
 */

/** Colourways the pack ships a House PNG for. */
type HouseColor = 'blue' | 'yellow' | 'red' | 'purple';

const CC0_BASE = '/assets/themes/tiny-swords-cc0';
const BUILDINGS = `${CC0_BASE}/Factions/Knights/Buildings`;
const GOBLIN_HOUSE = `${CC0_BASE}/Factions/Goblins/Buildings/Wood_House`;
/** User-authored custom building PNGs. Replace the stock CC0 buildings
 * for all 8 agent activities. */
const CUSTOM_BUILDINGS = `${CC0_BASE}/BuildingsCustom`;

/** Absolute filesystem path to the CC0 theme root. Resolved relative to
 * this file so `bun test` and `bun start` both find the assets without
 * depending on cwd. */
const CC0_ABS_ROOT = join(import.meta.dir, '../../../client/public/assets/themes/tiny-swords-cc0');
const CC0_WEB_ROOT = '/assets/themes/tiny-swords-cc0';

function buildTilesets(): TilesetManifest[] {
  return [
    {
      key: 'terrain-color1',
      label: 'Terrain — Flat grass',
      path: `${CC0_BASE}/Terrain/Ground/Tilemap_Flat.png`,
      tileWidth: 64,
      tileHeight: 64,
      columns: 10,
      rows: 4,
    },
    {
      key: 'terrain-color2',
      label: 'Terrain — Elevation',
      path: `${CC0_BASE}/Terrain/Ground/Tilemap_Elevation.png`,
      tileWidth: 64,
      tileHeight: 64,
      columns: 4,
      rows: 8,
    },
    {
      // Single 64×64 water tile — paint large water bodies on the grid.
      key: 'terrain-water',
      label: 'Terrain — Water',
      path: `${CC0_BASE}/Terrain/Water/Water.png`,
      tileWidth: 64,
      tileHeight: 64,
      columns: 1,
      rows: 1,
    },
  ];
}

function buildCc0DecorationsFromScan(): DecorationManifest[] {
  const assets = scanTheme(CC0_ABS_ROOT, CC0_WEB_ROOT, {
    // BuildingsCustom: protected-building PNGs, referenced explicitly by
    // buildProtectedBuildings(); they must not appear in the decoration palette.
    // Terrain/Ground: tileset atlases (Tilemap_Flat, Tilemap_Elevation) already
    // surfaced via buildTilesets(). Terrain/Water and Terrain/Bridge stay in-
    // scope so water tiles, foam, rocks and bridge decorations reach the palette.
    excludeDirs: ['Terrain/Ground', 'BuildingsCustom'],
    excludeFiles: [/\.aseprite$/i, /^\.DS_Store$/i, /^LICENSE/i, /^README/i],
  });
  const out: DecorationManifest[] = [];
  for (const asset of assets) {
    const entry = applyRules(asset, CC0_PACK_RULES);
    if (entry !== null) out.push(entry);
  }
  return out;
}

/** Pre-branch CC0 manifest used hand-curated keys (`bush-1`, `rock-1`,
 * `tree-1..4`, `house-{color}-{variant}`). Saved maps authored with
 * those keys still reference them. Emit aliases that point to the same
 * PNGs so those maps render without migration. Hidden from the palette
 * (empty folderPath + empty group → TileTree skips). */
function buildLegacyAliases(): DecorationManifest[] {
  const ROOT = CC0_BASE;
  const out: DecorationManifest[] = [];

  // Bushes 1–4 → Deco/01–04
  for (let i = 1; i <= 4; i++) {
    out.push({
      key: `bush-${i}`,
      label: `Bush ${i} (legacy)`,
      path: `${ROOT}/Deco/${String(i).padStart(2, '0')}.png`,
      category: 'bush',
      group: '',
      folderPath: [],
      defaultScale: 0.55,
    });
  }
  // Stumps 1–4 → Deco/05–08
  for (let i = 0; i < 4; i++) {
    const n = 5 + i;
    out.push({
      key: `stump-${i + 1}`,
      label: `Stump ${i + 1} (legacy)`,
      path: `${ROOT}/Deco/${String(n).padStart(2, '0')}.png`,
      category: 'stump',
      group: '',
      folderPath: [],
      defaultScale: 0.6,
    });
  }
  // Rocks 1–4 → Deco/09–12
  for (let i = 0; i < 4; i++) {
    const n = 9 + i;
    out.push({
      key: `rock-${i + 1}`,
      label: `Rock ${i + 1} (legacy)`,
      path: `${ROOT}/Deco/${String(n).padStart(2, '0')}.png`,
      category: 'rock',
      group: '',
      folderPath: [],
      defaultScale: 0.6,
    });
  }
  // Trees 1–4 → Tree.png (192×192 atlas, frame picker)
  for (let i = 1; i <= 4; i++) {
    out.push({
      key: `tree-${i}`,
      label: `Tree ${i} (legacy)`,
      path: `${ROOT}/Resources/Trees/Tree.png`,
      category: 'tree',
      group: '',
      folderPath: [],
      frameWidth: 192,
      frameHeight: 192,
      defaultScale: 0.9,
    });
  }
  // water-bg → Water.png. Pre-branch maps painted large sea areas by
  // scattering hundreds of `water-bg` decorations; alias them to the
  // 64×64 CC0 water tile so those maps still render without a migration.
  out.push({
    key: 'water-bg',
    label: 'Water BG (legacy)',
    path: `${ROOT}/Terrain/Water/Water.png`,
    category: 'water',
    group: '',
    folderPath: [],
    defaultScale: 1.0,
  });
  // Houses: 5 logical colours × 4 variants. Black falls back to purple.
  const colorToCc0: Record<string, HouseColor> = {
    blue: 'blue', yellow: 'yellow', red: 'red', purple: 'purple', black: 'purple',
  };
  const cap = (s: string): string => s[0]!.toUpperCase() + s.slice(1);
  for (const logical of ['blue', 'yellow', 'red', 'purple', 'black']) {
    const cc0 = cap(colorToCc0[logical]!);
    for (const variant of ['house1', 'house2', 'house3', 'tower'] as const) {
      let path: string;
      if (variant === 'house1')       path = `${BUILDINGS}/House/House_${cc0}.png`;
      else if (variant === 'house2')  path = `${BUILDINGS}/House/House_Construction.png`;
      else if (variant === 'house3')  path = `${BUILDINGS}/House/House_Destroyed.png`;
      else                            path = `${BUILDINGS}/Tower/Tower_${cc0}.png`;
      out.push({
        key: `house-${logical}-${variant}`,
        label: `${cap(logical)} ${variant === 'tower' ? 'Tower' : `House ${variant.replace('house', '')}`} (legacy)`,
        path,
        category: 'house',
        group: '',
        folderPath: [],
        defaultScale: 0.45,
      });
    }
  }
  return out;
}

function buildProtectedBuildings(): ProtectedBuildingManifest[] {
  // Same 8-activity mapping used by the main VillageScene — keep in sync
  // with CC0_BUILDINGS in client/src/game/themes/tiny-swords-cc0.ts.
  return [
    { id: 'library',    label: 'Library',    path: `${CUSTOM_BUILDINGS}/Library.png`,       activity: 'reading',   defaultScale: 0.40 },
    { id: 'alchemist',  label: 'Alchemist',  path: `${CUSTOM_BUILDINGS}/Alchemist.png`,     activity: 'debugging', defaultScale: 0.35 },
    { id: 'castle',     label: 'Castle',     path: `${CUSTOM_BUILDINGS}/Castle.png`,        activity: 'thinking',  defaultScale: 0.45 },
    { id: 'watchtower', label: 'Watchtower', path: `${CUSTOM_BUILDINGS}/Tower.png`,         activity: 'reviewing', defaultScale: 0.35 },
    { id: 'chapel',     label: 'Chapel',     path: `${CUSTOM_BUILDINGS}/Chapel.png`,        activity: 'git',       defaultScale: 0.35 },
    { id: 'tavern',     label: 'Tavern',     path: `${CUSTOM_BUILDINGS}/Tavern.png`,        activity: 'idle',      defaultScale: 0.40 },
    { id: 'forge',      label: 'Forge',      path: `${CUSTOM_BUILDINGS}/Forge.png`,         activity: 'editing',   defaultScale: 0.40 },
    { id: 'arena',      label: 'Arena',      path: `${CUSTOM_BUILDINGS}/Arena.png`,         activity: 'bash',      defaultScale: 0.35 },
  ];
}

export function buildAssetManifestCc0(): AssetManifest {
  return {
    tilesets: buildTilesets(),
    decorations: [...buildCc0DecorationsFromScan(), ...buildLegacyAliases()],
    protectedBuildings: buildProtectedBuildings(),
  };
}
